apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: converter-ui
  name: converter-ui
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: converter-ui
    spec:
      containers:
      - env:
        - name: GET_HOSTS_FROM
          value: dns
        image: jsincl4ir/converter-ui:latest
        name: converter-ui
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
