apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: converter-ui
  name: converter-ui
spec:
  externalIPs:
  - 192.168.1.138
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4200
  selector:
    io.kompose.service: converter-ui
status:
  loadBalancer:
    ingress:
    - ip: 146.148.47.155
