version: "3"

services:
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_ROOT_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    networks:
      - converternet
  springboot-api:
    image: "jsincl4ir/converter-api:latest"
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - AWS_REGION=local
      - ENVIRONMENT=local
      - AUTH_ENABLED=false
    networks:
      - converternet
  converter-ui:
    image: "jsincl4ir/converter-ui:latest"
    depends_on:
      - springboot-api
    ports:
      - "4200:80"
    networks:
      - converternet
    environment:
      - GET_HOSTS_FROM=dns
networks:
  converternet:
    driver: bridge
